backend:
  name: git-gateway
  branch: master
  repo: mateki0/ModernSimple
media_folder: static/assets
public_folder: /assets
collections:
  - name: 'images'
    label: 'Zdjęcia'
    folder: 'static/content/portfolio/images'
    create: true
    fields:
      - { name: 'imgName', label: 'Nazwa zdjęcia', required: true }
      - { name: 'imgDescription', label: 'Opis zdjęcia', required: true }
      - {
          name: 'category',
          label: 'Kategorie',
          widget: 'relation',
          collection: 'image-categories',
          searchFields: ['title'],
          valueField: 'title',
          required: true,
        }
      - { name: 'image', label: 'Zdjęcie', widget: 'image', required: true }

  - name: 'image-categories'
    label: 'Kategorie Zdjęć'
    folder: 'static/content/portfolio/categories'
    create: true
    fields:
      - { label: 'Nazwa Kategorii dla zdjęć', name: 'title', widget: 'string', required: true }
      - {
          label: 'Tytuł podstrony dla kategorii artkułów',
          name: 'pageTitle',
          widget: 'string',
          required: true,
        }
